version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3.8.3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'

  service2:
    image: service2
    build:
      context: .
      dockerfile: Service2/Dockerfile
    depends_on:
      - "rabbitmq"
    ports:
     - 9001:80


  service1:
    image: service1
    build:
      context: .
      dockerfile: Service1/Dockerfile
    depends_on:
     - "rabbitmq"
    ports:
     - 9002:80

volumes:
  rabbitmq_data:

